package com.bank;
import com.bank.AdminService;
import com.bank.SecurityUtil;

public class TestHash {

     public static void main(String[] args) {
        try {
            AdminService adminService = new AdminService();
            BankService bankService = new BankService();
          
            String password = "Ani123";
            // Show hash generated by Java
            String hash = SecurityUtil.hashPassword(password);
            System.out.println("Java hashed password: " + hash);

            // Attempt login
            boolean success = bankService.login(1, password);
            System.out.println("Login success? " + success);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
